title: Dr. Pothireddy Surendranath Reddy
email: bvsubbareddyortho@gmail.com
description: >
  Official medical articles, research, and professional profile of
  Dr. Pothireddy Surendranath Reddy â€“ Orthopaedic Surgeon,
  Joint Replacement & Arthroscopy Specialist.

baseurl: ""
url: "https://pothireddysurendranathreddy.github.io"

theme: minima

author:
  name: Dr. Pothireddy Surendranath Reddy

plugins:
  - jekyll-seo-tag

minima:
  skin: auto
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/pothireddy-surendranath-reddy-a980b438a" }
    - { platform: youtube, user_url: "https://www.youtube.com/@srp3597" }
    - { platform: twitter, user_url: "https://x.com/pothireddy1196" }

header_pages:
  - index.md
